name: thunder_vpn
description: Thunder Vpn
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  app_tracking_transparency: ^2.0.4
  cached_network_image: ^3.3.0
  country_codes: ^3.1.0+2
  country_icons: ^2.0.2
  dart_ping: ^9.0.1
  dio: ^5.3.3
  easy_localization: ^3.0.3
  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.5
  flutter_html: ^3.0.0-alpha.6
  flutter_inapp_purchase: ^5.6.1
  #    git:
  #      url: https://github.com/nizwar/flutter_inapp_purchase.git
  google_fonts: ^6.1.0
  google_mobile_ads: ^5.2.0
  in_app_update: ^4.2.2
  lottie: ^2.6.0
  ndialog: ^4.4.0
  openvpn_flutter: ^1.3.3
  package_info_plus: ^4.2.0
  provider: ^6.0.5
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  # for the supabase connection
  supabase_flutter: ^2.8.0
  #for converting the CSV file
  csv: ^6.0.0
  #for saving the file
  path_provider: ^2.0.11



dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"
    - "assets/images/maps/"
    - "assets/icons/"
    - "assets/animations/"
    - "assets/languages/"
    - "assets/html/"
